# Generated by Django 5.2.8 on 2025-12-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_route_unique_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirplaneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('purpose', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Airplane Type',
                'verbose_name_plural': 'Airplane Types',
                'ordering': ['code'],
            },
        ),
    ]
