# Generated by Django 5.2.8 on 2025-12-07 17:00

import service.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_airplanetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('country', models.CharField(max_length=50)),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(null=True, upload_to=service.utils.create_manufacturer_logo_url)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
                'ordering': ['-created_at'],
            },
        ),
    ]
