# Generated by Django 5.2.8 on 2025-12-12 13:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rows', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seats_in_row', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pilots_capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
                ('personal_capacity', models.PositiveSmallIntegerField(default=0)),
                ('year_of_manufacture', models.PositiveSmallIntegerField()),
                ('fuel_capacity_l', models.PositiveIntegerField()),
                ('cargo_capacity_kg', models.PositiveIntegerField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airplanes', to='service.manufacturer')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airplanes', to='service.airplanetype')),
            ],
        ),
    ]
