# Generated by Django 5.2.8 on 2025-12-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_airplane'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airplane',
            options={'ordering': ['year_of_manufacture'], 'verbose_name': 'Airplane', 'verbose_name_plural': 'Airplanes'},
        ),
        migrations.AddField(
            model_name='airplane',
            name='max_distance_km',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airplane',
            name='max_speed_kmh',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
