# Generated by Django 5.2.8 on 2025-12-12 14:09

import service.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_airplane_options_airplane_max_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='image',
            field=models.ImageField(null=True, upload_to=service.utils.create_airplane_image_url),
        ),
    ]
