# Generated by Django 5.2.8 on 2025-12-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_airplane_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(('source', models.F('destination')), _negated=True), name='source_not_equal_destination'),
        ),
    ]
