# Generated by Django 5.2.8 on 2025-12-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_route_source_not_equal_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('crew_type', models.CharField(choices=[('flight_crew', 'Flight crew'), ('cabin_crew', 'Cabin crew')], max_length=20)),
                ('position', models.CharField(choices=[('captain', 'Captain'), ('co_pilot', 'Co-Pilot'), ('flight_engineer', 'Flight Engineer'), ('navigator', 'Navigator'), ('flight_attendant', 'Flight Attendant'), ('senior_flight_attendant', 'Senior Flight Attendant'), ('safety_officer', 'Safety Officer')], max_length=30)),
            ],
            options={
                'indexes': [models.Index(fields=['first_name', 'last_name'], name='service_cre_first_n_c56412_idx')],
            },
        ),
    ]
