# Generated by Django 5.2.8 on 2026-01-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_flight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['departure_time'], 'verbose_name': 'Flight', 'verbose_name_plural': 'Flights'},
        ),
    ]
