# Generated by Django 5.2.8 on 2026-01-05 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='row',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
